export type Product = {
  id: string;
  categorySlug: string;
  brandName: string;
  productName: string;
  price: number;
  imageUrl: string;
  purchaseUrl: string;
  affiliateUrl?: string;
  originalUrl?: string;
  summary: string;
  reasons: string[];
  recommendedFor?: string[];
  notRecommendedFor?: string[];
  priceRange?: string;
  purchasePlace?: string;
  isSponsored?: boolean;
  sponsorshipLabel?: string;
  lastCheckedAt?: string;
};
