import type { Category } from "@/types/category";
import type { Product } from "@/types/product";

export const categories: Category[] = [
  {
    id: "1",
    name: "양말",
    slug: "socks",
    emoji: "🧦",
    description: "매일 신는 기본 크루삭스",
    statusLabel: "정착 완료",
    shortLine: "매일 신는 건 이걸로",
    isReady: true,
  },
  {
    id: "2",
    name: "팬티",
    slug: "underwear",
    emoji: "🩲",
    description: "편하고 오래 입는 기본 드로즈",
    statusLabel: "재구매 중",
    shortLine: "편한 건 오래 감",
    isReady: true,
  },
  {
    id: "3",
    name: "벨트",
    slug: "belt",
    emoji: "👔",
    description: "정장·캐주얼 모두 되는 기본 벨트",
    statusLabel: "이걸로 끝",
    shortLine: "튀지 않고 오래 쓰는 것",
    isReady: true,
  },
  {
    id: "4",
    name: "립밤",
    slug: "lip-balm",
    emoji: "🫦",
    description: "가방에 하나 넣어두는 립밤",
    statusLabel: "준비 중",
    shortLine: "곧 추가됩니다",
    isReady: false,
  },
  {
    id: "5",
    name: "베개",
    slug: "pillow",
    emoji: "🛏️",
    description: "바꾸면 바로 차이 나는 수면 베개",
    statusLabel: "준비 중",
    shortLine: "곧 추가됩니다",
    isReady: false,
  },
  {
    id: "6",
    name: "검정 이너티",
    slug: "black-inner-tee",
    emoji: "🖤",
    description: "아무 옷 안에 받쳐 입는 검정 이너티",
    statusLabel: "준비 중",
    shortLine: "곧 추가됩니다",
    isReady: false,
  },
  {
    id: "7",
    name: "수건",
    slug: "towel",
    emoji: "🛁",
    description: "막 쓰기 좋은 기본 수건",
    statusLabel: "계속 이거",
    shortLine: "매일 쓰는 건 무난하게",
    isReady: true,
  },
  {
    id: "8",
    name: "슬리퍼",
    slug: "slippers",
    emoji: "🥿",
    description: "집에서 하루 종일 신기 좋은 실내화",
    statusLabel: "집에서 고정",
    shortLine: "집 안에서 계속 신는 것",
    isReady: true,
  },
];

export const products: Product[] = [
  {
    id: "p1",
    categorySlug: "socks",
    brandName: "Standard Socks",
    productName: "데일리 코튼 크루삭스 5족",
    price: 12900,
    imageUrl: "",
    purchaseUrl: "https://example.com/socks",
    affiliateUrl: "https://example.com/socks",
    summary: "색 튀지 않고, 세탁해도 늘어나지 않는 양말. 더 고민할 필요 없습니다.",
    reasons: [
      "무채색이라 어떤 신발에도 그냥 신을 수 있음",
      "세탁 10회 넘어도 발목 밴드가 늘어지지 않음",
      "5족 묶음이라 한 번 사두면 두 달은 편함",
    ],
    recommendedFor: [
      "양말 고를 시간을 없애고 싶은 사람",
      "출퇴근용으로 무난하게 쓸 것을 찾는 사람",
      "세탁기 돌려도 금방 망가지지 않는 걸 원하는 사람",
    ],
    notRecommendedFor: [
      "발목 위로 올라오는 긴 양말이 필요한 사람",
      "발 냄새 차단 기능이 중요한 사람",
    ],
    priceRange: "1만 원대",
    purchasePlace: "쿠팡 / 네이버 쇼핑",
    lastCheckedAt: "2026-06",
  },
  {
    id: "p2",
    categorySlug: "underwear",
    brandName: "Daily Underwear",
    productName: "코튼 드로즈 3매",
    price: 24900,
    imageUrl: "",
    purchaseUrl: "https://example.com/underwear",
    affiliateUrl: "https://example.com/underwear",
    summary: "허리 밴드가 하루 종일 안 불편한 팬티. 면 소재라 피부 자극도 없습니다.",
    reasons: [
      "허리 밴드가 좁고 탄탄해서 흘러내리지 않음",
      "100% 면이라 오래 입어도 피부가 답답하지 않음",
      "색이 무난해 옷 입을 때 고민 필요 없음",
    ],
    recommendedFor: [
      "오래 앉아 일하는 사람",
      "피부 민감해서 소재 신경 쓰는 사람",
      "매일 같은 거 사서 재고 관리 없애고 싶은 사람",
    ],
    notRecommendedFor: [
      "드라이핏이나 기능성 소재를 선호하는 사람",
      "타이트한 핏을 좋아하는 사람",
    ],
    priceRange: "2만 원대",
    purchasePlace: "쿠팡 / 올리브영",
    lastCheckedAt: "2026-06",
  },
  {
    id: "p3",
    categorySlug: "belt",
    brandName: "Plain Belt Co.",
    productName: "클래식 레더 벨트",
    price: 19900,
    imageUrl: "",
    purchaseUrl: "https://example.com/belt",
    affiliateUrl: "https://example.com/belt",
    summary: "정장에도, 청바지에도 튀지 않는 벨트. 버클이 작아서 어디에나 어울립니다.",
    reasons: [
      "버클 크기가 작아 캐주얼·포멀 모두 가능",
      "검정과 갈색 두 가지라 웬만한 바지에 매칭됨",
      "가죽 마감이 깔끔해서 저렴해 보이지 않음",
    ],
    recommendedFor: [
      "벨트 하나로 오래 쓰고 싶은 사람",
      "출퇴근복과 캐주얼을 같이 커버하고 싶은 사람",
    ],
    notRecommendedFor: [
      "큰 버클 디자인을 좋아하는 사람",
      "합성 피혁이 아닌 천연 가죽만 원하는 사람",
    ],
    priceRange: "1만 원대 후반",
    purchasePlace: "쿠팡 / 무신사",
    lastCheckedAt: "2026-05",
  },
  {
    id: "p7",
    categorySlug: "towel",
    brandName: "Soft Towel",
    productName: "호텔 타월 2장",
    price: 21900,
    imageUrl: "",
    purchaseUrl: "https://example.com/towel",
    affiliateUrl: "https://example.com/towel",
    summary: "흡수는 되는데 금방 마르는 수건. 두꺼운 수건 특유의 냄새 문제가 없습니다.",
    reasons: [
      "얇지 않은데 건조 속도가 빠름",
      "세탁 여러 번 해도 보풀이 많이 생기지 않음",
      "사이즈가 커서 한 장으로 충분함",
    ],
    recommendedFor: [
      "수건 냄새 때문에 자주 세탁하는 사람",
      "두꺼운 수건이 안 마르는 게 불편한 사람",
    ],
    notRecommendedFor: [
      "두툼하고 폭신한 촉감을 원하는 사람",
      "색이 다양한 수건을 원하는 사람",
    ],
    priceRange: "2만 원대",
    purchasePlace: "쿠팡",
    lastCheckedAt: "2026-04",
  },
  {
    id: "p8",
    categorySlug: "slippers",
    brandName: "Home Step",
    productName: "메모리폼 실내화",
    price: 17900,
    imageUrl: "",
    purchaseUrl: "https://example.com/slippers",
    affiliateUrl: "https://example.com/slippers",
    summary: "발바닥이 눌리지 않고 오래 신을 수 있는 실내화. 바닥 소음도 거의 없습니다.",
    reasons: [
      "메모리폼 밑창이 발 피로를 줄여줌",
      "바닥 마찰이 적어 집 안에서 소음이 없음",
      "디자인이 단순해서 어느 공간에도 어울림",
    ],
    recommendedFor: [
      "집에서 하루 종일 신을 실내화를 찾는 사람",
      "층간 소음 신경 쓰이는 사람",
    ],
    notRecommendedFor: [
      "야외에서도 신고 싶은 사람",
      "발 고정이 필요한 작업을 하는 사람",
    ],
    priceRange: "1만 원대",
    purchasePlace: "쿠팡 / 다이소",
    lastCheckedAt: "2026-05",
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getProductByCategorySlug(slug: string): Product | undefined {
  return products.find((p) => p.categorySlug === slug);
}
